Boolean indexing

In [2]:
import numpy as np
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a[a>4] = 0
a

array([[0, 1, 2, 3, 4],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [5]:
print(a)
a[a==0] =-1
a

[[0 1 2 3 4]
 [0 0 0 0 0]
 [0 0 0 0 0]]


array([[-1,  1,  2,  3,  4],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1]])

In [8]:
a == -1

array([[ True, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [9]:
a = np.arange(12).reshape(3,4)
print(a)
a[np.logical_and(a>3,a<=9)] = 0.0
a

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1,  2,  3],
       [ 0,  0,  0,  0],
       [ 0,  0, 10, 11]])

In [10]:
a >4

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True]])

In [11]:
a = np.arange(12).reshape(3,4)
print(a)
a[np.logical_or(a>3,a<=9)] = 0.0
a

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

Avoiding loops

In [12]:
M = 32
N = 64
xmin = ymin = 0.0
xmax = ymax = 1.0
x = np.linspace(xmin,xmax,M, endpoint=False)
y = np.linspace(ymin,ymax,N, endpoint=True)
print(x.shape)
print(y.shape)
print(x)
y

(32,)
(64,)
[0.      0.03125 0.0625  0.09375 0.125   0.15625 0.1875  0.21875 0.25
 0.28125 0.3125  0.34375 0.375   0.40625 0.4375  0.46875 0.5     0.53125
 0.5625  0.59375 0.625   0.65625 0.6875  0.71875 0.75    0.78125 0.8125
 0.84375 0.875   0.90625 0.9375  0.96875]


array([0.        , 0.01587302, 0.03174603, 0.04761905, 0.06349206,
       0.07936508, 0.0952381 , 0.11111111, 0.12698413, 0.14285714,
       0.15873016, 0.17460317, 0.19047619, 0.20634921, 0.22222222,
       0.23809524, 0.25396825, 0.26984127, 0.28571429, 0.3015873 ,
       0.31746032, 0.33333333, 0.34920635, 0.36507937, 0.38095238,
       0.3968254 , 0.41269841, 0.42857143, 0.44444444, 0.46031746,
       0.47619048, 0.49206349, 0.50793651, 0.52380952, 0.53968254,
       0.55555556, 0.57142857, 0.58730159, 0.6031746 , 0.61904762,
       0.63492063, 0.65079365, 0.66666667, 0.68253968, 0.6984127 ,
       0.71428571, 0.73015873, 0.74603175, 0.76190476, 0.77777778,
       0.79365079, 0.80952381, 0.82539683, 0.84126984, 0.85714286,
       0.87301587, 0.88888889, 0.9047619 , 0.92063492, 0.93650794,
       0.95238095, 0.96825397, 0.98412698, 1.        ])

In [13]:
import time
M = 32
N = 64
x = np.linspace(0.0,1.0,M, endpoint=False)
y = np.linspace(0.0,1.0,N, endpoint= False)

In [14]:
t0 = time.time()
 
g = np.zeros((M,N))
print(g)
for i in range(M):
    for j in range(N):
        g[i,j] = np.sin(2.0*np.pi*x[i]*y[j])
print(g)
t1 = time.time()
print(f'time elapsed : {t1-t0} s')

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.00306796  0.00613588 ...  0.18605515  0.18906866
   0.1920804 ]
 [ 0.          0.00613588  0.01227154 ...  0.365613    0.37131719
   0.37700741]
 ...
 [ 0.          0.08885355  0.17700422 ... -0.75520138 -0.69397146
  -0.62725182]
 [ 0.          0.09190896  0.18303989 ... -0.62005721 -0.54532499
  -0.4659765 ]
 [ 0.          0.0949635   0.18906866 ... -0.46325978 -0.37700741
  -0.28734746]]
time elapsed : 0.033998727798461914 s


In [15]:
x2d,y2d = np.meshgrid(x,y, indexing ="ij")
 
print(x2d[:,0])
print(x2d[0,:])
 
print(y2d[:,0])
print(y2d[0,:])

[0.      0.03125 0.0625  0.09375 0.125   0.15625 0.1875  0.21875 0.25
 0.28125 0.3125  0.34375 0.375   0.40625 0.4375  0.46875 0.5     0.53125
 0.5625  0.59375 0.625   0.65625 0.6875  0.71875 0.75    0.78125 0.8125
 0.84375 0.875   0.90625 0.9375  0.96875]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
[0.       0.015625 0.03125  0.046875 0.0625   0.078125 0.09375  0.109375
 0.125    0.140625 0.15625  0.171875 0.1875   0.203125 0.21875  0.234375
 0.25     0.265625 0.28125  0.296875 0.3125   0.328125 0.34375  0.359375
 0.375    0.390625 0.40625  0.421875 0.4375   0.453125 0.46875  0.484375
 0.5      0.515625 0.53125  0.546875 0.5625   0.578125 0.59375  0.609375
 0.625    0.640625 0.65625  0.671875 0.6875   0.703125 0.71875  0.734375
 0.75     

In [16]:
t0 = time.time()
g2= np.sin(2.0*np.pi*x2d*y2d)
t1= time.time()
print(f'time elapsed: {t1-t0}seconds')

time elapsed: 0.0seconds


Array concatenation and splitting

In [17]:
x = np.array ([1,2,3,4])
y = np.array ([5,6,7,8])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
z = np.array([9,10,11])
#z = [9,10,11] this creates only a list
print(np.concatenate([x,y,z]))
type(z)

[ 1  2  3  4  5  6  7  8  9 10 11]


numpy.ndarray

In [19]:
grid = np.array([[10,20,30],
[40,50,60]])
print(grid)
print(grid.shape)
grid.ndim

[[10 20 30]
 [40 50 60]]
(2, 3)


2

In [20]:
np.concatenate([grid,grid])

array([[10, 20, 30],
       [40, 50, 60],
       [10, 20, 30],
       [40, 50, 60]])

In [21]:
np.concatenate([grid,grid],axis=1)

array([[10, 20, 30, 10, 20, 30],
       [40, 50, 60, 40, 50, 60]])

Splitting of arrays

In [22]:
x = [1,2,3,4,6,9,8,7,5,0]
x1,x2,x3,x4 = np.split(x,[3,5,8])
print(x1,x2,x3,x4)

[1 2 3] [4 6] [9 8 7] [5 0]


In [24]:
g = np.arange(16).reshape(4,4)
g

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [26]:
left, right = np.hsplit(g,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [27]:
top,bottom = np.vsplit(g,[2])
print(top)
print(bottom)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


Aggregate

In [30]:
x = np.arange(1,15)
print(x)
np.add.reduce(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


105

In [31]:
np.multiply.reduce(x)

1278945280

In [32]:
print(np.add.accumulate(x))
x

[  1   3   6  10  15  21  28  36  45  55  66  78  91 105]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
print(np.multiply.accumulate(x))
x

[         1          2          6         24        120        720
       5040      40320     362880    3628800   39916800  479001600
 1932053504 1278945280]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])